export const auditStateNames = ['focus', 'interaction', 'active'] as const

export type UiAuditState = (typeof auditStateNames)[number]

export const auditComponentNames = [
  'FixedSizeList',
  'DynamicSizeList',
  'FixedSizeGrid',
  'DynamicSizeGrid',
  'ElVisuallyHidden',
  'ElAffix',
  'ElAlert',
  'ElAside',
  'ElAutocomplete',
  'ElAvatar',
  'ElBacktop',
  'ElBadge',
  'ElBreadcrumb',
  'ElBreadcrumbItem',
  'ElButton',
  'ElButtonGroup',
  'ElCalendar',
  'ElCard',
  'ElCarousel',
  'ElCarouselItem',
  'ElCascader',
  'ElCascaderPanel',
  'ElCheckbox',
  'ElCheckboxButton',
  'ElCheckboxGroup',
  'ElCheckTag',
  'ElCol',
  'ElCollapse',
  'ElCollapseItem',
  'ElCollapseTransition',
  'ElColorPicker',
  'ElConfigProvider',
  'ElContainer',
  'ElCountdown',
  'ElDatePicker',
  'ElDescriptions',
  'ElDescriptionsItem',
  'ElDialog',
  'ElDivider',
  'ElDrawer',
  'ElDropdown',
  'ElDropdownItem',
  'ElDropdownMenu',
  'ElEmpty',
  'ElEmptyState',
  'ElFooter',
  'ElForm',
  'ElFormItem',
  'ElHeader',
  'ElIcon',
  'ElImage',
  'ElImageViewer',
  'ElInput',
  'ElInputNumber',
  'ElLink',
  'ElMain',
  'ElMarkdownEditor',
  'ElMarkdownRenderer',
  'ElMetricList',
  'ElMenu',
  'ElMenuItem',
  'ElMenuItemGroup',
  'ElOption',
  'ElOptionGroup',
  'ElOverlay',
  'ElPageHeader',
  'ElPublicShell',
  'ElPagination',
  'ElPopconfirm',
  'ElPopover',
  'ElPopper',
  'ElPopperArrow',
  'ElPopperContent',
  'ElPopperTrigger',
  'ElProgress',
  'ElRadio',
  'ElRadioButton',
  'ElRadioGroup',
  'ElRate',
  'ElResult',
  'ElResponsiveCollection',
  'ElRow',
  'ElScrollbar',
  'ElSelect',
  'ElSelectV2',
  'ElSlider',
  'ElSkeleton',
  'ElSkeletonItem',
  'ElSpace',
  'ElStatistic',
  'ElStep',
  'ElSteps',
  'ElSubMenu',
  'ElSwitch',
  'ElTabPane',
  'ElTable',
  'ElTableColumn',
  'ElAutoResizer',
  'ElTableV2',
  'ElTabs',
  'ElTag',
  'ElText',
  'ElThemeModeToggle',
  'ElTimePicker',
  'ElTimeSelect',
  'ElTimeline',
  'ElTimelineItem',
  'ElTooltip',
  'ElTooltipV2',
  'ElTransfer',
  'ElTree',
  'ElTreeSelect',
  'ElTreeV2',
  'ElUpload',
  'ElWatermark',
] as const

export type UiAuditComponentName = (typeof auditComponentNames)[number]

const focusLocatorOverrides: Partial<Record<UiAuditComponentName, string>> = {
  ElCheckbox: '.el-checkbox__original',
  ElCheckboxButton: '.el-checkbox-button__original',
  ElCheckboxGroup: '.el-checkbox__original',
  ElInputNumber: '.el-input__inner',
  ElLink: '.el-link',
  ElOption: '.el-select__wrapper',
  ElOptionGroup: '.el-select__wrapper',
  ElRadio: '.el-radio__original',
  ElRadioButton: '.el-radio-button__original-radio',
  ElRadioGroup: '.el-radio__original',
  ElSelect: '.el-select__wrapper',
  ElSelectV2: '.el-select-v2__combobox-input',
  ElTimeSelect: '.el-input__inner',
  ElTreeSelect: '.el-select__wrapper',
}

export const auditComponents = auditComponentNames.map((name) => ({
  name,
  route: '/?audit=ui-states',
  locator: `[data-audit-component="${name}"]`,
  focusLocator: `[data-audit-component="${name}"] ${
    focusLocatorOverrides[name] ?? '[data-audit-focus]'
  }`,
  interactionLocator: `[data-audit-component="${name}"] [data-audit-target]`,
  activeLocator: `[data-audit-component="${name}"] [data-audit-active]`,
}))
