const fs = require('fs');
const path = 'packages/theme-chalk/src/fsus-theme.scss';
let content = fs.readFileSync(path, 'utf8');
const finalStyle = '\n// =============================================================================\n// DEFINITIVE GEOMETRIC CALIBRATION (v5.0)\n// =============================================================================\n\n.#{$namespace}-button,\n.#{$namespace}-input__wrapper,\n.#{$namespace}-textarea__inner,\n.#{$namespace}-select-v2__wrapper,\n.#{$namespace}-select__wrapper,\n.#{$namespace}-tag,\n.#{$namespace}-alert,\n.#{$namespace}-message,\n.#{$namespace}-notification,\n.#{$namespace}-pagination button,\n.#{$namespace}-pagination .btn-prev,\n.#{$namespace}-pagination .btn-next,\n.#{$namespace}-pager li,\n.#{$namespace}-checkbox__inner,\n.#{$namespace}-radio__inner,\n.#{$namespace}-switch__core {\n  border-radius: 12px !important;\n}\n\n.#{$namespace}-select-dropdown__item,\n.#{$namespace}-select-dropdown__option-item,\n.#{$namespace}-dropdown-menu__item,\n.#{$namespace}-cascader-node,\n.#{$namespace}-autocomplete-suggestion li,\n.#{$namespace}-picker-panel__shortcut,\n.#{$namespace}-tree-node__content {\n  border-radius: 14px !important;\n  margin: 4px 8px !important;\n  padding: 0 16px !important;\n  min-height: 44px !important;\n  display: flex !important;\n  align-items: center !important;\n}\n\n.#{$namespace}-card,\n.#{$namespace}-dialog,\n.#{$namespace}-drawer,\n.#{$namespace}-message-box {\n  border-radius: 24px !important;\n}\n\n.#{$namespace}-popper,\n.#{$namespace}-select-dropdown,\n.#{$namespace}-dropdown-menu,\n.#{$namespace}-cascader__dropdown,\n.#{$namespace}-picker__popper,\n.#{$namespace}-autocomplete__popper,\n.#{$namespace}-tooltip__popper {\n  border-radius: 20px !important;\n  padding: 6px !important;\n}\n';
if (content.indexOf('// =============================================================================') !== -1) {
    content = content.split('// =============================================================================')[0];
}
content += finalStyle;
fs.writeFileSync(path, content);
