const fs = require('fs');
const path = 'packages/theme-chalk/src/fsus-theme.scss';
let content = fs.readFileSync(path, 'utf8');
const nuclearStyle = '\n// =============================================================================\n// NUCLEAR RADIUS & ALIGNMENT FIX (v4.0)\n// =============================================================================\n\n:root {\n  --el-border-radius-base: 12px !important;\n  --el-border-radius-small: 8px !important;\n  --el-border-radius-large: 24px !important;\n  --el-card-border-radius: 24px !important;\n  --el-dialog-border-radius: 24px !important;\n  --el-popover-border-radius: 20px !important;\n  --el-messagebox-border-radius: 24px !important;\n}\n\n.#{$namespace}-checkbox__inner,\n.#{$namespace}-radio__inner,\n.#{$namespace}-switch__core,\n.#{$namespace}-input-number .#{$namespace}-input-number__increase,\n.#{$namespace}-input-number .#{$namespace}-input-number__decrease {\n  border-radius: 8px !important; \n}\n\n.#{$namespace}-button,\n.#{$namespace}-input__wrapper,\n.#{$namespace}-textarea__inner,\n.#{$namespace}-select__wrapper,\n.#{$namespace}-tag,\n.#{$namespace}-alert,\n.#{$namespace}-message,\n.#{$namespace}-notification {\n  border-radius: 12px !important; \n}\n\n.#{$namespace}-select-dropdown__item,\n.#{$namespace}-select-dropdown__option-item,\n.#{$namespace}-dropdown-menu__item,\n.#{$namespace}-cascader-node,\n.#{$namespace}-autocomplete-suggestion li,\n.#{$namespace}-picker-panel__shortcut {\n  border-radius: 14px !important;\n  margin: 4px 6px !important; \n  padding: 0 16px !important;\n  min-height: 44px !important;\n  display: flex !important;\n  align-items: center !important;\n}\n\n.#{$namespace}-tree-node__content {\n  height: auto !important;\n  min-height: 44px !important;\n}\n\n.#{$namespace}-tree-node__expand-icon {\n  margin-left: 8px !important;\n}\n';
if (content.indexOf('// =============================================================================') !== -1) {
    content = content.split('// =============================================================================')[0];
}
content += nuclearStyle;
fs.writeFileSync(path, content);
