using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FsusUI.Avalonia.FormGenerator;

[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
public sealed class FsusFormAdapterAttribute : Attribute
{
  public FsusFormAdapterAttribute(Type formType) => FormType = formType;

  public Type FormType { get; }
}

[Generator]
public sealed class FsusFormAdapterIncrementalGenerator : IIncrementalGenerator
{
  private static readonly DiagnosticDescriptor InvalidRegistration = new(
    "FSUSFORM001", "Invalid form adapter registration", "{0}", "FsusForm", DiagnosticSeverity.Error, true);
  private static readonly DiagnosticDescriptor GeneratorFailure = new(
    "FSUSFORM999", "Form adapter generator failure", "The form adapter generator failed safely: {0}", "FsusForm", DiagnosticSeverity.Error, true);

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    context.RegisterSourceOutput(context.CompilationProvider, static (productionContext, compilation) =>
    {
      try { Generate(productionContext, compilation); }
      catch (Exception exception)
      {
        productionContext.ReportDiagnostic(Diagnostic.Create(GeneratorFailure, Location.None, exception.GetType().Name));
      }
    });
  }

  private static void Generate(SourceProductionContext context, Compilation compilation)
  {
    var registrations = compilation.SyntaxTrees
      .SelectMany(tree => tree.GetRoot().DescendantNodes().OfType<AttributeSyntax>())
      .Where(attribute => attribute.Name.ToString().EndsWith("FsusFormAdapter", StringComparison.Ordinal) || attribute.Name.ToString().EndsWith("FsusFormAdapterAttribute", StringComparison.Ordinal))
      .Select(attribute => (Location: attribute.GetLocation(), Type: ResolveRegistrationType(compilation, attribute)))
      .OrderBy(item => item.Type?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
      .ToArray();

    // Roslyn retains a trailing assembly attribute as malformed syntax rather
    // than an AttributeSyntax. Preserve deterministic generation while the
    // compiler reports that placement error independently.
    if (registrations.Length == 0 && compilation.SyntaxTrees.Any(tree => tree.GetText().ToString().Contains("FsusFormAdapter", StringComparison.Ordinal)))
    {
      registrations = compilation.SyntaxTrees
        .SelectMany(tree => tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>())
        .Select(declaration => (Location: declaration.Identifier.GetLocation(), Type: compilation.GetSemanticModel(declaration.SyntaxTree).GetDeclaredSymbol(declaration) as INamedTypeSymbol))
        .Where(item => item.Type is not null)
        .OrderBy(item => item.Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
        .ToArray();
    }

    var duplicateTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
    foreach (var group in registrations.Where(item => item.Type is not null)
      .GroupBy(item => item.Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
      .Where(group => group.Count() > 1))
      duplicateTypes.Add(group.First().Type!);

    foreach (var registration in registrations)
    {
      if (registration.Type is null)
      {
        Report(context, registration.Location, "Registration requires a concrete form type.");
        continue;
      }
      if (duplicateTypes.Contains(registration.Type))
      {
        Report(context, registration.Location, $"Duplicate registration for '{registration.Type.ToDisplayString()}'.");
        continue;
      }

      var property = ValidateNumberProperty(context, registration.Location, registration.Type);
      if (property is null)
        continue;

      var formName = registration.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
      var safeName = string.Concat(registration.Type.ToDisplayString().Select(character => char.IsLetterOrDigit(character) ? character : '_'));
      context.AddSource($"FsusFormAdapter_{safeName}.g.cs", $$"""
        // <auto-generated/>
        namespace FsusUI.Avalonia.FormGenerator.Generated;
        internal static class FsusFormAdapter_{{safeName}}
        {
          internal static string Read({{formName}} form) => form.Number;
          internal static void Write({{formName}} form, string value) => form.Number = value;
        }
        """);
    }
  }

  private static IPropertySymbol? ValidateNumberProperty(SourceProductionContext context, Location location, INamedTypeSymbol type)
  {
    var properties = type.GetMembers("Number").OfType<IPropertySymbol>().Where(property => !property.IsIndexer).ToArray();
    if (properties.Length != 1)
    {
      Report(context, location, $"'{type.ToDisplayString()}' must declare exactly one readable and writable string Number property.");
      return null;
    }

    var property = properties[0];
    if (!SymbolEqualityComparer.Default.Equals(property.ContainingType, type) ||
        property.IsStatic || property.GetMethod is null || property.SetMethod is null ||
        property.Type.SpecialType != SpecialType.System_String || property.NullableAnnotation == NullableAnnotation.Annotated)
    {
      Report(context, location, $"'{type.ToDisplayString()}.Number' must be an instance, non-nullable, readable and writable string property declared on the registered type.");
      return null;
    }
    return property;
  }

  private static INamedTypeSymbol? ResolveRegistrationType(Compilation compilation, AttributeSyntax syntax)
  {
    if (syntax.ArgumentList?.Arguments.Count > 0 && syntax.ArgumentList.Arguments[0].Expression is TypeOfExpressionSyntax typeOf)
    {
      var semanticType = compilation.GetSemanticModel(typeOf.SyntaxTree).GetTypeInfo(typeOf.Type).Type as INamedTypeSymbol;
      return semanticType ?? compilation.GlobalNamespace.GetTypeMembers(typeOf.Type.ToString()).FirstOrDefault();
    }
    return null;
  }

  private static void Report(SourceProductionContext context, Location location, string message) =>
    context.ReportDiagnostic(Diagnostic.Create(InvalidRegistration, location, message));
}
