import installer from './defaults'
export * from '@element-plus/components'
export * from '@element-plus/constants'
export * from '@element-plus/directives'
export * from '@element-plus/hooks'
export * from './make-installer'
export * from './render-pipeline-policies'
export * from './result'
export {
  FsuBottomActionBar,
  FsuMobileDock,
  FsuMotion,
  FsuMotionRecipe,
  FsuOverlayTransition,
  FsuRowStateMotion,
  FsuScrollTimeline,
  FsuSheetTransition,
  FsuSharedElement,
  FsuTaskReceipt,
  FsuToastReceipt,
  FsuTransition,
  cancelMotion,
  claimMotionBudgetNode,
  createMotionRouteCleanup,
  createMotionPlugin,
  defaultMotionBudget,
  getMotionPhaseState,
  getMotionBudget,
  getMotionPreset,
  getMotionPresetSurfaces,
  getMotionRecipe,
  getPrefersReducedMotion,
  getGsap,
  getGsapPresetVars,
  isScrollTriggerRegistered,
  isMotionPresetAllowedOnSurface,
  isMotionPresetName,
  isMotionPropertyAllowed,
  isMotionRecipeName,
  isMotionReducedOrDisabled,
  killScrollTriggersFor,
  millisecondsToSeconds,
  motion,
  motionCssVars,
  motionPresetAliases,
  motionTokenAliases,
  motionPresets as motionPresetDefinitions,
  motionRecipes,
  motionTokens,
  normalizeMotionOptions,
  normalizeMotionRecipeOptions,
  playFlipMotion,
  readingMotionPolicy,
  readingMotionPresetNames,
  refreshScrollTriggers,
  registerScrollTrigger,
  releaseMotionBudgetNode,
  resolveMotionBudget,
  resolveMotionPreference,
  resolveMotionPresetName,
  resolveMotionRecipeName,
  resolveMotionScrollBehavior,
  resolveMotionTarget,
  sanitizeGsapVars,
  runMotion,
  runMotionRecipe,
  setMotionBudget,
  assertEveryPresetHasGovernanceMetadata,
  validateMotionAdoptionMapping,
  validateMotionPresetUsage,
  useGsapContext,
  useFlipMotion,
  useMotionRouteCleanup,
  useMotionPreference,
  useScrollReveal,
  useRowStateMotion,
  useScrollTimeline,
  useSharedElementMotion,
  useTaskFeedback,
  useTimeline,
  vMotion,
  vScrollReveal,
} from '@element-plus/motion'
export type {
  GsapContextCallback,
  GsapScope,
  FlipMotionOptions,
  FlipMotionState,
  MotionDirectiveValue,
  MotionBudgetConfig,
  MotionOptions,
  MotionPhase,
  MotionPluginConfig,
  MotionPresetDefinition,
  MotionPresetName,
  MotionRecipeDefinition,
  MotionRecipeName,
  MotionSurfaceCategory,
  MotionRecipeOptions,
  MotionRecipeValue,
  MotionRunOptions,
  MotionRuntimeControls,
  MotionStyleState,
  MotionTarget,
  MotionTimelineStep,
  RowStateEntry,
  RowStateKey,
  RowStateMotionUpdate,
  RowStatePhase,
  UseRowStateMotionOptions,
  MotionMode,
  MotionPreferenceSnapshot,
  MotionAdoptionEntry,
  MotionEffectKind,
  MotionGovernanceFinding,
  MotionGovernanceSeverity,
  MotionInteractionKind,
  MotionPresetUsage,
  ScrollRevealOptions,
  ScrollRevealRunOptions,
  ScrollTimelineSegment,
  SharedElementTarget,
  UseScrollTimelineOptions,
  UseTimelineOptions,
  TaskFeedbackPhase,
  TaskFeedbackUpdate,
  UseTaskFeedbackOptions,
  MotionTokens,
} from '@element-plus/motion'

export const install = installer.install
export const version = installer.version
export { groupedInstaller } from './defaults'
export default installer

export { default as dayjs } from 'dayjs'
