import installer from './defaults'
export * from '@element-plus/components'
export * from '@element-plus/constants'
export * from '@element-plus/directives'
export * from '@element-plus/hooks'
export * from './make-installer'
export * from './render-pipeline-policies'
export * from './result'
export {
  FsuMotion,
  FsuMotionRecipe,
  FsuScrollTimeline,
  FsuSharedElement,
  FsuTransition,
  cancelMotion,
  claimMotionBudgetNode,
  createMotionRouteCleanup,
  createMotionPlugin,
  defaultMotionBudget,
  getMotionPhaseState,
  getMotionBudget,
  getMotionPreset,
  getMotionRecipe,
  getPrefersReducedMotion,
  getGsap,
  getGsapPresetVars,
  isScrollTriggerRegistered,
  isMotionPresetName,
  isMotionPropertyAllowed,
  isMotionRecipeName,
  isMotionReducedOrDisabled,
  killScrollTriggersFor,
  millisecondsToSeconds,
  motion,
  motionCssVars,
  motionTokenAliases,
  motionPresets as motionPresetDefinitions,
  motionRecipes,
  motionTokens,
  normalizeMotionOptions,
  normalizeMotionRecipeOptions,
  playFlipMotion,
  refreshScrollTriggers,
  registerScrollTrigger,
  releaseMotionBudgetNode,
  resolveMotionBudget,
  resolveMotionPreference,
  resolveMotionPresetName,
  resolveMotionRecipeName,
  resolveMotionScrollBehavior,
  resolveMotionTarget,
  sanitizeGsapVars,
  runMotion,
  runMotionRecipe,
  setMotionBudget,
  useGsapContext,
  useFlipMotion,
  useMotionRouteCleanup,
  useMotionPreference,
  useScrollReveal,
  useScrollTimeline,
  useSharedElementMotion,
  useTimeline,
  vMotion,
  vScrollReveal,
} from '@element-plus/motion'
export type {
  GsapContextCallback,
  GsapScope,
  FlipMotionOptions,
  FlipMotionState,
  MotionDirectiveValue,
  MotionBudgetConfig,
  MotionOptions,
  MotionPhase,
  MotionPluginConfig,
  MotionPresetDefinition,
  MotionPresetName,
  MotionRecipeDefinition,
  MotionRecipeName,
  MotionRecipeOptions,
  MotionRecipeValue,
  MotionRunOptions,
  MotionRuntimeControls,
  MotionStyleState,
  MotionTarget,
  MotionTimelineStep,
  MotionMode,
  MotionPreferenceSnapshot,
  ScrollRevealOptions,
  ScrollRevealRunOptions,
  ScrollTimelineSegment,
  SharedElementTarget,
  UseScrollTimelineOptions,
  UseTimelineOptions,
  MotionTokens,
} from '@element-plus/motion'

export const install = installer.install
export const version = installer.version
export { groupedInstaller } from './defaults'
export default installer

export { default as dayjs } from 'dayjs'
