export {
  defaultRenderPipelineConfig,
  isRenderPipelineConfigValid,
  normalizeRenderPipelineConfig,
} from '@element-plus/components/config-provider'

export type {
  RenderPipelineAccelerationConfig,
  RenderPipelineAdaptiveMode,
  RenderPipelineBudget,
  RenderPipelineCompositorMode,
  RenderPipelineConfigContract,
  RenderPipelineHardwareMode,
  RenderPipelineMode,
  RenderPipelineThresholds,
  RenderPipelineWorkerMode,
  ResolvedRenderPipelineConfig,
} from '@element-plus/components/config-provider'

export {
  chooseFsusRenderPipelineStrategy,
  clearFsusRenderPipelineAdapters,
  clearFsusRenderPipelineDiagnostics,
  clearFsusRenderPipelineComponentPolicies,
  clearFsusRenderPipelineStrategyResolvers,
  createFsusRenderPipelineComponentPolicies,
  createFsusRenderPipelineComponentPolicy,
  createFsusRenderPipelineDiagnosticsBuffer,
  createFsusWorkerExecutor,
  getFsusComponentName,
  getFsusRenderPipelineAdapter,
  getFsusRenderPipelineComponentPolicy,
  getFsusRenderPipelineDiagnosticsSnapshot,
  listFsusRenderPipelineAdapters,
  listFsusRenderPipelineComponentPolicies,
  registerFsusDefaultRenderPipelineComponentPolicies,
  registerFsusRenderPipelineAdapter,
  registerFsusRenderPipelineComponentPolicies,
  registerFsusRenderPipelineComponentPolicy,
  registerFsusRenderPipelineComponentPolicyByName,
  registerFsusRenderPipelineDiagnosticSink,
  registerFsusRenderPipelineStrategyResolver,
  resolveFsusInstallComponentName,
  resolveFsusAdaptiveRenderPipelineConfig,
  resolveFsusRenderPipelineCache,
  resolveFsusRenderPipelineCompositorEnabled,
  resolveFsusRenderPipelineComponentPolicy,
  resolveFsusRenderPipelineConfig,
  resolveFsusRenderPipelineContentVisibilityEnabled,
  resolveFsusRenderPipelineHardwareAttrs,
  resolveFsusRenderPipelineHardwareProfile,
  resolveFsusRenderPipelineUnitAttrs,
  shouldUseFsusRenderPipeline,
  useFsusRenderPipeline,
  useFsusRenderPipelineHardwareProfile,
  useFsusRenderPipelineRuntime,
  useFsusRenderScheduler,
  useFsusVirtualWindow,
} from '@element-plus/hooks'

export type {
  FsusRenderDocument,
  FsusRenderEstimate,
  FsusRenderHardwareProfile,
  FsusRenderPipelineDomAttrs,
  FsusRenderPipelineAdapter,
  FsusRenderPipelineAccelerationConfig,
  FsusRenderPipelineAdaptiveMode,
  FsusRenderPipelineAdaptiveSignals,
  FsusRenderPipelineComponentEstimate,
  FsusRenderPipelineComponentPolicy,
  FsusRenderPipelineComponentRole,
  FsusRenderPipelineCompositorMode,
  FsusRenderPipelineConfig,
  FsusRenderPipelineDocument,
  FsusRenderPipelineEstimate,
  FsusRenderPipelineHardwareMode,
  FsusRenderPipelineMode,
  FsusRenderPipelineRuntimeOptions,
  FsusRenderPipelineRuntimeState,
  FsusRenderPipelineState,
  FsusRenderPipelineStrategy,
  FsusRenderPipelineStrategyContext,
  FsusRenderPipelineStrategyResolver,
  FsusRenderPipelineStrategyResolverOptions,
  FsusRenderPipelineUnitAttrsOptions,
  FsusRenderPipelineDiagnosticEvent,
  FsusRenderPipelineDiagnosticSink,
  FsusRenderPipelineDiagnosticsBuffer,
  FsusRenderSchedulerPriority,
  FsusRenderSchedulerTaskOptions,
  FsusResolvedRenderPipelineAcceleration,
  FsusRenderPipelineWorkerOptions,
  FsusRenderPipelineWorkerPoolMode,
  FsusRenderPipelineWorkerMode,
  FsusResolvedRenderPipelineComponentPolicy,
  FsusResolvedRenderPipelineConfig,
  FsusViewport,
  FsusVirtualWindowItem,
  FsusWorkerExecutorEvent,
  FsusWorkerExecutorEventType,
  FsusWorkerExecutorOptions,
} from '@element-plus/hooks'
