// @vitest-environment happy-dom
import { writeFileSync } from 'node:fs'
import { createHash, webcrypto } from 'node:crypto'
import { ElMarkdownRenderer } from '@ozwasyd/element-plus'
import { mount } from '@vue/test-utils'
import blogFixture from './markdown-embed-projection-blog-coordinate.json'
import * as runtime from '@ozwasyd/element-plus/markdown-runtime'
import { afterEach, describe, expect, it, vi } from 'vitest'

// Coordinates/reference map the shared ArticleEmbedDependencyCoordinate and
// ArticleEmbedSafeProjectionReference, not a route or title-derived identity.
// Generated by serializing the actual C# coordinate/reference records and
// ComputeDependency at the exact active Blog producer revision (see handoff).
const target = blogFixture.coordinate.target.portableArticleIdentity
const source = blogFixture.source
const digest = (value: string) =>
  createHash('sha256').update(value, 'utf8').digest('hex')
const targetVersion = {
  targetIdentity: target,
  resolvedRevision: String(blogFixture.coordinate.resolvedRevision),
  targetVersionIdentity: blogFixture.coordinate.targetVersionIdentity,
  projectionIdentity: blogFixture.projection.projectionIdentity,
  projectionDigest: '0'.repeat(64),
}

afterEach(() => vi.unstubAllGlobals())

const boundFixture = async (body = source) => {
  vi.stubGlobal('crypto', webcrypto)
  const request = await runtime.createMarkdownEmbedProjectionRequest({
    documentIdentity: { id: 'document:host', epoch: 3 },
    revision: 8,
    nodeId: 'embed:one',
    target,
    mode: 'article',
    version: 1,
  })
  let current = { ...targetVersion, projectionDigest: digest(body) }
  const result = {
    ...request,
    status: 'resolved' as const,
    targetVersion: current,
    title: 'Authorized source',
    projection: {
      kind: 'markdown' as const,
      projectionIdentity: current.projectionIdentity,
      contentDigest: current.projectionDigest,
      source: body,
    },
  }
  const authority = { readTargetVersion: () => current }
  return {
    request,
    result,
    authority,
    update: () => {
      current = {
        ...current,
        resolvedRevision: '18',
        targetVersionIdentity: 'article-version:18',
      }
    },
  }
}

const nodeOf = () => {
  const node = runtime.collectMarkdownEmbedNodes(
    `::embed[target="${target}" mode="article"]`,
  )[0]!
  if (!node.ok) throw new Error(node.code)
  return node
}

describe('article embed controlled projection public boundary', () => {
  it('refuses content whose bytes do not match the supplied projection reference', () => {
    const request = runtime.createMarkdownEmbedRequest({
      documentIdentity: { id: 'document:host', epoch: 3 },
      revision: 8,
      nodeId: 'embed:one',
      target,
      mode: 'article',
      version: 1,
    })
    const result = {
      ...request,
      status: 'resolved' as const,
      targetVersion,
      projection: {
        kind: 'markdown' as const,
        projectionIdentity: targetVersion.projectionIdentity,
        contentDigest: targetVersion.projectionDigest,
        source,
      },
    }
    expect(runtime.commitMarkdownEmbedResult(request, result).status).toBe(
      'rejected',
    )
  })

  it('renders verified Markdown through the real public renderer without expanding host source', async () => {
    const fixture = await boundFixture()
    const prepared = await runtime.prepareMarkdownEmbedResult(
      fixture.request,
      fixture.result,
      fixture.authority,
    )
    expect(runtime.commitMarkdownEmbedResult(fixture.request, prepared)).toBe(
      prepared,
    )
    const node = nodeOf()
    const presentation = runtime.resolveMarkdownEmbedPresentation(
      { kind: 'valid', node, result: prepared, request: fixture.request },
      'preview',
    )
    expect(presentation.state).toBe('resolved')
    expect(presentation.content.markdown).toBe(source)
    expect(presentation.content.editable).toBe(false)
    expect(presentation.content.html).toBeNull()
    ;(
      window as unknown as { happyDOM: { setURL: (url: string) => void } }
    ).happyDOM.setURL('http://localhost:3000/')
    const wrapper = mount(ElMarkdownRenderer, {
      props: { content: presentation.content.markdown!, mode: 'preview' },
    })
    try {
      await expect
        .poll(() => wrapper.find('strong').exists(), { timeout: 2000 })
        .toBe(true)
      expect(wrapper.find('strong').text()).toBe('controlled')
      expect(wrapper.find('textarea').exists()).toBe(false)
      expect(wrapper.find('[contenteditable="true"]').exists()).toBe(false)
      expect(presentation.directive).toBe(
        `::embed[target="${target}" mode="article"]`,
      )
      if (process.env.FSUSUI_EMBED_PROJECTION_EVIDENCE) {
        writeFileSync(
          process.env.FSUSUI_EMBED_PROJECTION_EVIDENCE,
          wrapper.html(),
        )
      }
    } finally {
      wrapper.unmount()
    }
  })

  it.each([
    'requestId',
    'requestDigest',
    'revision',
    'nodeId',
    'target',
    'mode',
    'version',
    'document',
    'epoch',
  ] as const)('refuses controlled content after %s drift', async (field) => {
    const fixture = await boundFixture()
    const changed =
      field === 'document'
        ? { ...fixture.result, documentIdentity: { id: 'other', epoch: 3 } }
        : field === 'epoch'
          ? {
              ...fixture.result,
              documentIdentity: { id: 'document:host', epoch: 4 },
            }
          : {
              ...fixture.result,
              ...{
                requestId: { requestId: 'other' },
                requestDigest: { requestDigest: digest('other') },
                revision: { revision: 9 },
                nodeId: { nodeId: 'other' },
                target: { target: 'other' },
                mode: { mode: 'heading' as const },
                version: { version: 2 },
              }[field],
            }
    expect(
      (
        await runtime.prepareMarkdownEmbedResult(
          fixture.request,
          changed,
          fixture.authority,
        )
      ).status,
    ).toBe('stale')
  })

  it('checks actual bytes, current exact target version, projection identity and cancellation', async () => {
    const fixture = await boundFixture()
    const wrongBytes = {
      ...fixture.result,
      projection: { ...fixture.result.projection, source: 'changed' },
    }
    expect(
      await runtime.prepareMarkdownEmbedResult(
        fixture.request,
        wrongBytes,
        fixture.authority,
      ),
    ).toMatchObject({
      status: 'rejected',
      reason: 'projection-digest-mismatch',
    })
    const wrongIdentity = {
      ...fixture.result,
      projection: { ...fixture.result.projection, projectionIdentity: 'other' },
    }
    expect(
      (
        await runtime.prepareMarkdownEmbedResult(
          fixture.request,
          wrongIdentity,
          fixture.authority,
        )
      ).status,
    ).toBe('rejected')
    const prepared = await runtime.prepareMarkdownEmbedResult(
      fixture.request,
      fixture.result,
      fixture.authority,
    )
    fixture.update()
    expect(
      runtime.commitMarkdownEmbedResult(fixture.request, prepared).status,
    ).toBe('stale')
    expect(
      runtime.resolveMarkdownEmbedPresentation(
        {
          kind: 'valid',
          node: nodeOf(),
          result: prepared,
          request: fixture.request,
        },
        'live',
      ).content.markdown,
    ).toBeNull()
    const cancelled = await boundFixture()
    let finish!: (source: string) => void
    const pending = runtime.prepareMarkdownEmbedResult(
      cancelled.request,
      {
        ...cancelled.result,
        projection: {
          kind: 'markdown-reference',
          projectionIdentity: cancelled.result.projection.projectionIdentity,
          contentDigest: cancelled.result.projection.contentDigest,
        },
      },
      {
        ...cancelled.authority,
        resolveMarkdown: () =>
          new Promise<string>((resolve) => {
            finish = resolve
          }),
      },
    )
    runtime.cancelMarkdownEmbedRequest(cancelled.request)
    finish(source)
    expect((await pending).status).toBe('stale')
  })

  it('resolves a real local reference and refuses unknown executable output', async () => {
    const fixture = await boundFixture()
    const reference = {
      kind: 'markdown-reference' as const,
      projectionIdentity: fixture.result.projection.projectionIdentity,
      contentDigest: fixture.result.projection.contentDigest,
    }
    const prepared = await runtime.prepareMarkdownEmbedResult(
      fixture.request,
      { ...fixture.result, projection: reference },
      { ...fixture.authority, resolveMarkdown: () => source },
    )
    expect(
      runtime.commitMarkdownEmbedResult(fixture.request, prepared).status,
    ).toBe('resolved')
    expect(
      (
        await runtime.prepareMarkdownEmbedResult(
          fixture.request,
          { ...fixture.result, projection: reference },
          fixture.authority,
        )
      ).status,
    ).toBe('rejected')
    const unsafe = {
      ...fixture.result,
      html: '<iframe src="https://example.test"></iframe>',
    }
    expect(
      runtime.commitMarkdownEmbedResult(fixture.request, unsafe).status,
    ).toBe('rejected')
    expect(
      (
        await runtime.prepareMarkdownEmbedResult(
          fixture.request,
          unsafe,
          fixture.authority,
        )
      ).status,
    ).toBe('rejected')
    const forged = { ...prepared }
    expect(
      runtime.commitMarkdownEmbedResult(fixture.request, forged).status,
    ).toBe('rejected')
  })

  it('keeps unsafe Markdown inside the existing URL and feature output gateway', async () => {
    const body =
      'Safe **body** [bad](javascript:alert(1))\n\n<script>alert(1)</script>\n<iframe src="https://example.test"></iframe>\n'
    const fixture = await boundFixture(body)
    const prepared = await runtime.prepareMarkdownEmbedResult(
      fixture.request,
      fixture.result,
      fixture.authority,
    )
    const presentation = runtime.resolveMarkdownEmbedPresentation(
      {
        kind: 'valid',
        node: nodeOf(),
        result: prepared,
        request: fixture.request,
      },
      'preview',
    )
    const wrapper = mount(ElMarkdownRenderer, {
      props: { content: presentation.content.markdown!, mode: 'preview' },
    })
    try {
      await expect
        .poll(() => wrapper.find('strong').exists(), { timeout: 2000 })
        .toBe(true)
      expect(
        wrapper
          .find('script,iframe,object,embed,[contenteditable="true"]')
          .exists(),
      ).toBe(false)
      expect(wrapper.find('a[href^="javascript:"]').exists()).toBe(false)
      expect(wrapper.emitted('render-error')).toBeUndefined()
    } finally {
      wrapper.unmount()
    }
  })
})
