//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("FsusUI")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.0.0-preview.0+90a7d58aad585edbbeec8756fc6d6e5aa0a2c9a7")]
[assembly: System.Reflection.AssemblyProductAttribute("FsusUI.Avalonia.HeadlessTests")]
[assembly: System.Reflection.AssemblyTitleAttribute("FsusUI.Avalonia.HeadlessTests")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/Ozwasyd/FsusUI")]
[assembly: System.Reflection.AssemblyMetadata("Microsoft.Testing.Platform.Application", "true")]

// Generated by the MSBuild WriteCodeFragment class.

