export {
  MARKDOWN_POINTER_PLATFORMS,
  createMarkdownAnchorMap,
  type MarkdownAnchorAffinity,
  type MarkdownAnchorMap,
  type MarkdownAnchorMapInput,
  type MarkdownAnchorSyntaxInput,
  type MarkdownAnchorSyntaxNode,
  type MarkdownAnchorSyntaxRange,
  type MarkdownHiddenTraversal,
  type MarkdownHiddenTraversalDirection,
  type MarkdownHiddenTraversalQuery,
  type MarkdownPointerHit,
  type MarkdownPointerPlatform,
  type MarkdownPointerSourcePosition,
  type MarkdownRangeMutation,
  type MarkdownRemappedRange,
  type MarkdownRevealHighlight,
  type MarkdownRevealQuery,
  type MarkdownRevealTarget,
  type MarkdownSelectionDirection,
  type MarkdownSourcePosition,
  type MarkdownSourceReveal,
  type MarkdownSourceSelection,
  type MarkdownVisualKind,
  type MarkdownVisualPoint,
  type MarkdownVisualPointName,
  type MarkdownVisualPointQuery,
  type MarkdownVisualSelection,
  type SourceSelection,
} from '../../../wasm/markdown-anchor-map'
