export {
  createMarkdownAnchorMap,
  type MarkdownAnchorAffinity,
  type MarkdownAnchorMap,
  type MarkdownAnchorMapInput,
  type MarkdownAnchorSyntaxInput,
  type MarkdownAnchorSyntaxNode,
  type MarkdownAnchorSyntaxRange,
  type MarkdownRangeMutation,
  type MarkdownRemappedRange,
  type MarkdownRevealQuery,
  type MarkdownRevealTarget,
  type MarkdownSelectionDirection,
  type MarkdownSourcePosition,
  type MarkdownSourceSelection,
  type MarkdownVisualKind,
  type MarkdownVisualPoint,
  type MarkdownVisualPointName,
  type MarkdownVisualPointQuery,
  type MarkdownVisualSelection,
  type SourceSelection,
} from '../../../wasm/markdown-anchor-map'
