import installer from './defaults'
export * from '@element-plus/components'
export * from '@element-plus/constants'
export * from '@element-plus/directives'
export * from '@element-plus/hooks'
export * from './make-installer'
export * from './render-pipeline-policies'
export * from './result'
export { ElEmptyState } from '@element-plus/components/empty-state'
export { ElSiteHeader } from '@element-plus/components/site-header'
export {
  ElLocalizationChallenge,
  ElMicroInteractionChallenge,
  ElPerceptionCharacterChallenge,
  ElPerceptionChallenge,
  ElTextTaskChallenge,
  FsusLocalizationChallenge,
  FsusMicroInteractionChallenge,
  FsusPerceptionCharacterChallenge,
  FsusPerceptionChallenge,
  FsusTextTaskChallenge,
} from '@element-plus/components/perception-challenge'
export type {
  CharacterChallengeProps,
  PerceptionChallengeAssignment,
  PerceptionCharacterAudioMedia,
  PerceptionCharacterMedia,
  PerceptionCharacterMode,
  PerceptionCharacterSubmitPayload,
  PerceptionCharacterChallengeInstance,
  PerceptionChallengeClient,
  PerceptionChallengeExpiredPayload,
  PerceptionChallengeKind,
  PerceptionChallengeRenderPayload,
  PerceptionChallengeRenderer,
  PerceptionChallengeState,
  PerceptionChallengeSubmitPayload,
  PerceptionChallengeVerifyResult,
} from '@element-plus/components/perception-challenge'
export {
  FsuBottomActionBar,
  FsuBottomTabBar,
  FsuMobileDock,
  FsuMotion,
  FsuMotionRecipe,
  FsuOverlayTransition,
  FsuRowStateMotion,
  FsuScrollTimeline,
  FsuSheetTransition,
  FsuSharedElement,
  FsuTaskReceipt,
  FsuToastReceipt,
  FsuTransition,
  cancelMotion,
  claimMotionBudgetNode,
  createMotionRouteCleanup,
  createMotionPlugin,
  defaultMotionBudget,
  getMotionBudget,
  getMotionPhaseState,
  getMotionPreset,
  getMotionPresetSurfaces,
  getMotionRecipe,
  getPrefersReducedMotion,
  getGsap,
  getGsapPresetVars,
  isMotionPresetAllowedOnSurface,
  isMotionPresetName,
  isMotionPropertyAllowed,
  isMotionRecipeName,
  isMotionReducedOrDisabled,
  isScrollTriggerRegistered,
  killScrollTriggersFor,
  millisecondsToSeconds,
  motion,
  motionCssVars,
  motionPresetAliases,
  motionTokenAliases,
  motionPresets as motionPresetDefinitions,
  motionRecipes,
  motionTokens,
  normalizeMotionOptions,
  normalizeMotionRecipeOptions,
  playFlipMotion,
  readingMotionPolicy,
  readingMotionPresetNames,
  refreshScrollTriggers,
  registerScrollTrigger,
  releaseMotionBudgetNode,
  resolveMotionBudget,
  resolveMotionPreference,
  resolveMotionPresetName,
  resolveMotionRecipeName,
  resolveMotionScrollBehavior,
  resolveMotionTarget,
  runMotion,
  runMotionRecipe,
  runMotionRecipeUpdate,
  runViewTransition,
  sanitizeGsapVars,
  setMotionBudget,
  assertEveryPresetHasGovernanceMetadata,
  validateMotionAdoptionMapping,
  validateMotionPresetUsage,
  useFlipMotion,
  useGsapContext,
  useMotionPreference,
  useMotionRouteCleanup,
  useRowStateMotion,
  useScrollReveal,
  useScrollTimeline,
  useSharedElementMotion,
  useTaskFeedback,
  useTimeline,
  useViewTransition,
  vMotion,
  vScrollReveal,
} from '@element-plus/motion'
export type {
  FsuBottomTabItem,
  FlipMotionOptions,
  FlipMotionState,
  GsapContextCallback,
  GsapScope,
  MotionAdoptionEntry,
  MotionDirectiveValue,
  MotionBudgetConfig,
  MotionEffectKind,
  MotionGovernanceFinding,
  MotionGovernanceSeverity,
  MotionInteractionKind,
  MotionOptions,
  MotionPhase,
  MotionPluginConfig,
  MotionMode,
  MotionPreferenceSnapshot,
  MotionPresetDefinition,
  MotionPresetName,
  MotionPresetUsage,
  MotionRecipeDefinition,
  MotionRecipeName,
  MotionRecipeOptions,
  MotionRecipeValue,
  MotionRunOptions,
  MotionRuntimeControls,
  MotionStyleState,
  MotionSurfaceCategory,
  MotionTarget,
  MotionTimelineStep,
  MotionTokens,
  RowStateEntry,
  RowStateKey,
  RowStateMotionUpdate,
  RowStatePhase,
  ScrollRevealOptions,
  ScrollRevealRunOptions,
  ScrollTimelineSegment,
  SharedElementTarget,
  TaskFeedbackPhase,
  TaskFeedbackUpdate,
  UseRowStateMotionOptions,
  UseScrollTimelineOptions,
  UseTaskFeedbackOptions,
  UseTimelineOptions,
  SharedElementMotionOptions,
  SharedElementRunOptions,
  ViewTransitionMode,
  ViewTransitionRunOptions,
  ViewTransitionRunResult,
} from '@element-plus/motion'

export const install = installer.install
export const version = installer.version
export { groupedInstaller } from './defaults'
export default installer

export { default as dayjs } from 'dayjs'
