// Stable subpath module: `@ozwasyd/element-plus/motion`
//
// Preview public API for downstream consumers that need the motion runtime
// (plugin, directives, composables, runtime helpers, preset lookup, governance
// validators) without depending on the deep `@element-plus/motion` package
// path. Surface area mirrors the named exports documented in
// `vue/packages/element-plus/index.ts`; do not add internal-only exports here.

export {
  FsuBottomActionBar,
  FsuBottomTabBar,
  FsuMobileDock,
  FsuMotion,
  FsuMotionRecipe,
  FsuOverlayTransition,
  FsuRowStateMotion,
  FsuScrollTimeline,
  FsuSheetTransition,
  FsuSharedElement,
  FsuTaskReceipt,
  FsuToastReceipt,
  FsuTransition,
  cancelMotion,
  claimMotionBudgetNode,
  createMotionRouteCleanup,
  createMotionPlugin,
  defaultMotionBudget,
  getMotionBudget,
  getMotionPhaseState,
  getMotionPreset,
  getMotionPresetSurfaces,
  getMotionRecipe,
  getPrefersReducedMotion,
  getGsap,
  getGsapPresetVars,
  isMotionPresetAllowedOnSurface,
  isMotionPresetName,
  isMotionPropertyAllowed,
  isMotionRecipeName,
  isMotionReducedOrDisabled,
  isScrollTriggerRegistered,
  killScrollTriggersFor,
  millisecondsToSeconds,
  motion,
  motionCssVars,
  motionPresetAliases,
  motionTokenAliases,
  motionPresets as motionPresetDefinitions,
  motionRecipes,
  motionTokens,
  normalizeMotionOptions,
  normalizeMotionRecipeOptions,
  playFlipMotion,
  readingMotionPolicy,
  readingMotionPresetNames,
  refreshScrollTriggers,
  registerScrollTrigger,
  releaseMotionBudgetNode,
  resolveMotionBudget,
  resolveMotionPreference,
  resolveMotionPresetName,
  resolveMotionRecipeName,
  resolveMotionScrollBehavior,
  resolveMotionTarget,
  runMotion,
  runMotionRecipe,
  sanitizeGsapVars,
  setMotionBudget,
  assertEveryPresetHasGovernanceMetadata,
  validateMotionAdoptionMapping,
  validateMotionPresetUsage,
  useFlipMotion,
  useGsapContext,
  useMotionPreference,
  useMotionRouteCleanup,
  useRowStateMotion,
  useScrollReveal,
  useScrollTimeline,
  useSharedElementMotion,
  useTaskFeedback,
  useTimeline,
  vMotion,
  vScrollReveal,
} from '@element-plus/motion'

export type {
  FsuBottomTabItem,
  FlipMotionOptions,
  FlipMotionState,
  GsapContextCallback,
  GsapScope,
  MotionAdoptionEntry,
  MotionBudgetConfig,
  MotionDirectiveValue,
  MotionEffectKind,
  MotionGovernanceFinding,
  MotionGovernanceSeverity,
  MotionInteractionKind,
  MotionMode,
  MotionOptions,
  MotionPhase,
  MotionPluginConfig,
  MotionPreferenceSnapshot,
  MotionPresetDefinition,
  MotionPresetName,
  MotionPresetUsage,
  MotionRecipeDefinition,
  MotionRecipeName,
  MotionRecipeOptions,
  MotionRecipeValue,
  MotionRunOptions,
  MotionRuntimeControls,
  MotionStyleState,
  MotionSurfaceCategory,
  MotionTarget,
  MotionTimelineStep,
  MotionTokens,
  RowStateEntry,
  RowStateKey,
  RowStateMotionUpdate,
  RowStatePhase,
  ScrollRevealOptions,
  ScrollRevealRunOptions,
  ScrollTimelineSegment,
  SharedElementTarget,
  TaskFeedbackPhase,
  TaskFeedbackUpdate,
  UseRowStateMotionOptions,
  UseScrollTimelineOptions,
  UseTaskFeedbackOptions,
  UseTimelineOptions,
} from '@element-plus/motion'
