// <auto-generated />
// Generated by scripts/conformance-v2-evidence.mjs from fsusui.alignment.v2.
namespace FsusUI.Avalonia.Demo.Gallery;

internal static class FsusGeneratedAlignment
{
  public static IReadOnlySet<string> StableFamilies { get; } = new HashSet<string>(StringComparer.Ordinal)
  {

  };
}
